[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true

[build]
target = "x86_64-kernel.json"

[target.x86_64-kernel]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=-zmax-page-size=0x1000",
    "-C", "relocation-model=static",
]
